image:
  repository: pritunl/pritunl-zero
  tag: "1.0.3292.11"

service:
  type: ClusterIP
  port: 443

mongodb:
  enabled: true
  image:
    tag: 4.4.6-debian-10-r13
  auth:
    rootPassword: your-root-password
    username: your-db-username
    password: your-db-password
    database: your-db-name

  readinessProbe:
    enabled: true
    exec:
      command:
        - bash
        - -c
        - |
          /bitnami/scripts/readiness-probe.sh
    initialDelaySeconds: 20

  livenessProbe:
    enabled: true
    exec:
      command:
        - bash
        - -c
        - |
          /bitnami/scripts/liveness-probe.sh
    initialDelaySeconds: 20

  extraVolumes:
    - name: custom-mongo-probes
      configMap:
        name: override-mongo-probes
        defaultMode: 0555

  extraVolumeMounts:
    - name: custom-mongo-probes
      mountPath: /bitnami/scripts/readiness-probe.sh
      subPath: readiness-probe.sh
    - name: custom-mongo-probes
      mountPath: /bitnami/scripts/liveness-probe.sh
      subPath: liveness-probe.sh

pritunl:
  oidc:
    enabled: true
    client_id: "${OIDC_CLIENT_ID}"
    client_secret: "${OIDC_CLIENT_SECRET}"
    issuer_url: "https://auth.example.com"
    redirect_uri: "https://vpn.example.com/auth/callback"

ingress:
  enabled: true
  className: nginx
  clusterIssuer: letsencrypt-staging
  host: vpn.example.com
  tlsSecret: pritunl-tls
