image:
  repository: pritunl/pritunl-zero
  tag: "1.0.3292.11"
  pullPolicy: IfNotPresent

mongodb:
  enabled: true
  image:
    tag: 4.4.6-debian-10-r13
  auth:
    rootPassword: your-root-password
    username: your-db-username
    password: your-db-password
    database: your-db-name

  livenessProbe:
    enabled: true
    path: /opt/bitnami/scripts/mongodb/healthcheck.sh

  readinessProbe:
    enabled: true
    path: /opt/bitnami/scripts/mongodb/healthcheck.sh

  extraVolumes:
    - name: custom-mongo-probes
      configMap:
        name: override-mongo-probes
        defaultMode: 0555

  extraVolumeMounts:
    - name: custom-mongo-probes
      mountPath: /opt/bitnami/scripts/mongodb/healthcheck.sh
      subPath: readiness-probe.sh

service:
  type: ClusterIP

ingress:
  enabled: false

pritunl:
  oidc:
    enabled: false
    client_id: ""
    client_secret: ""
    issuer_url: ""
    redirect_uri: ""
