apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpn-pritunl-mongodb-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/mongodb
