apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-pritunl-mongodb
  namespace: vpn
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: vpn-pritunl
    meta.helm.sh/release-namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi
