apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pritunl-cert
  namespace: vpn
spec:
  secretName: pritunl-tls
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer
  dnsNames:
    - vpn.example.com
