apiVersion: v1
kind: Service
metadata:
  name: {{ include "vpn-pritunl.fullname" . }}
  labels:
    {{- include "vpn-pritunl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 443 }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "vpn-pritunl.selectorLabels" . | nindent 4 }}
