apiVersion: v1
kind: Service
metadata:
  name: vpn-pritunl
spec:
  type: {{ .Values.service.type }}
  selector:
    app: vpn-pritunl
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
