name: Helm Chart Lint & Dry Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Lint Helm chart
        run: helm lint .

      - name: Dry-run render (template compilation test)
        run: helm template vpn-pritunl . -f dev-values.yaml
